Feature/export gen cov stats
UMCUGenetics/ExonCov pull request #50
Opened 2021-09-02 08:38 UTC by ellendejong

Several new classes are added to provide coverage stats and can be given to third party users.

Azure ticket: https://dev.azure.com/umcu/LAB-Bioinformatics-Genetics/_workitems/edit/103595

2021-09-02 10:34 UTC, ellendejong commented on ExonCov/cli.py
> +    def retrieve_and_print_transcript_measurements(self, query, measurement_type):
@rernst I am wondering whether these functions `retrieve_and_print_transcript_measurements` and `retrieve_and_print_panel_measurements` should be private. What are your thoughts?

2021-09-02 12:58 UTC, ellendejong commented on ExonCov/cli.py
> +        sample_ids = [sample.id for sample in sample_set.samples]
I consider to make sample_set optional. When not provided, stats are retrieved for all samples in the database. For the `weighted_average`, I could consider to retrieve all sample_ids by an additional query to `Sample`.

2021-09-03 11:02 UTC, melferink commented on ExonCov/cli.py
> +        Option('--min_days', dest='min_days', type=int, default=0),
Why no single character option here like the others? (-m?)

2021-09-03 11:15 UTC, melferink commented on ExonCov/cli.py
> +class PrintAliasTable(Command):
Wouldn't it make more sense to call this ExportAlilasTable?

2021-09-03 11:16 UTC, melferink commented on ExonCov/cli.py
> +class PrintCovStatsSampleSet(Command):
Likewise:  ExportCovStatsSampleSet?

2021-09-03 12:02 UTC, melferink commented on ExonCov/cli.py
> +                'measurement_mean_coverage',
Spaces behind the comma?(help will look much more readable)

2021-09-03 12:03 UTC, melferink commented on ExonCov/cli.py
> +        Option('-s', '--sample_set_name', required=True, dest="sample_set_name"),
I would change this to sample_set_ID and not name.  ID does not have special characters (and is unique)

2021-09-03 12:04 UTC, melferink commented on ExonCov/cli.py
> +        sample_ids = [sample.id for sample in sample_set.samples]
Agree on this. For now, I think sample_set should be sufficient for the stakeholder request. 
But in the future more regular updates/  samples might be required.

2021-09-03 12:10 UTC, melferink commented on ExonCov/cli.py
> +                'measurement_mean_coverage',
I do see this is also the case in other, so probably normal convention.

2021-09-06 08:08 UTC, melferink commented on ExonCov/cli.py
> +                sampleset_samples=sample_set.samples, query=query, measurement_type=measurement_type),
Why the comma at the end?

2021-09-06 08:10 UTC, melferink commented on ExonCov/cli.py
> +    def retrieve_and_print_transcript_measurements(self, query, measurement_type):
I would include a logical order:  retrieve_and_print_panel_measurements first, then retrieve_and_print_transcript_measurements

2021-09-06 08:17 UTC, melferink commented on ExonCov/cli.py
> +        panels_measurements = OrderedDict()
Shouldn't this be panel_measurments ?

2021-09-06 08:26 UTC, melferink commented on ExonCov/cli.py
> +                    panels_measurements = OrderedDict()
Why again? Variable declared in line 809

2021-09-06 09:09 UTC, melferink commented on ExonCov/cli.py
> +        query = db.session.query(PanelVersion, TranscriptMeasurement).filter_by(active=True, validated=True).join(Transcript, PanelVersion.transcripts).join(
You probably want to make an exception here for gen-panels FULL_autosomal and FULL_TARGET.
Those are not true diagnostic panels (aggregate of all transcripts), and will consume most (if not almost all) compute resources/time.

See cli.py line 592

2021-09-06 09:19 UTC, melferink commented on ExonCov/cli.py
> +                        min=prev_panel_measurements[prev_panel]['min'],
I would change the variable name as this is a function in Python

2021-09-06 09:19 UTC, melferink commented on ExonCov/cli.py
> +                        max=prev_panel_measurements[prev_panel]['max'])
I would change the variable name as this is a function in Python

2021-09-06 09:28 UTC, melferink commented on ExonCov/cli.py
> +                    prev_transcript = panels_measurements[prev_panel]['transcripts'].keys()[-1]
Do you print the last transcript in the query/dict?

2021-09-06 10:44 UTC, ellendejong commented on ExonCov/cli.py
> +        Option('--min_days', dest='min_days', type=int, default=0),
No reason, except I could not think of a single character option that would could not be confused with max_days.
I will add the -m.

- [ ] Add single character option min_days.

2021-09-06 10:47 UTC, ellendejong commented on ExonCov/cli.py
> +class PrintAliasTable(Command):
I definitely can change it to match the param.
I followed previous code example:
`db_manager.add_command('export_panel_bed', cli.PrintPanelBed())`

- [ ] change `PrintAliasTable` to `ExportAliasTable`.

2021-09-06 10:48 UTC, ellendejong commented on ExonCov/cli.py
> +class PrintCovStatsSampleSet(Command):
See previous comment.

- [ ]  change `PrintCovStatsSampleSet` to `ExportCovStatsSampleSet`.

2021-09-06 10:49 UTC, ellendejong commented on ExonCov/cli.py
> +        Option('-s', '--sample_set_name', required=True, dest="sample_set_name"),
- [ ] `sample_set_name` to `sample_set_id`, options and query.

2021-09-06 10:54 UTC, ellendejong commented on ExonCov/cli.py
> +                'measurement_mean_coverage',
Simply adding a space will not work, since the helper function and print format is part of the optparse option-parser package. I can overwrite the formatter by defining custom function... I prefer not to, tbh.

2021-09-06 10:55 UTC, ellendejong commented on ExonCov/cli.py
> +        query = db.session.query(PanelVersion, TranscriptMeasurement).filter_by(active=True, validated=True).join(Transcript, PanelVersion.transcripts).join(
- [ ] exclude non diagnostic gene panels, such as FULL_autosomal and FULL_TARGET.

2021-09-06 10:56 UTC, ellendejong commented on ExonCov/cli.py
> +                sampleset_samples=sample_set.samples, query=query, measurement_type=measurement_type),
- [ ] remove unnecessary comma

2021-09-06 10:56 UTC, ellendejong commented on ExonCov/cli.py
> +    def retrieve_and_print_transcript_measurements(self, query, measurement_type):
- [ ] Change order functions.

2021-09-06 10:58 UTC, ellendejong commented on ExonCov/cli.py
> +                    prev_transcript = panels_measurements[prev_panel]['transcripts'].keys()[-1]
No, I see I do not. Thanks :)

- [ ] Fix code to print final/last transcript.

2021-09-06 10:58 UTC, ellendejong commented on ExonCov/cli.py
> +                    prev_panel = panels_measurements.keys()[-1]
No, I see I do not. Thanks :)
- [ ] Fix code to print final/last panel.

2021-09-07 07:15 UTC, melferink commented on ExonCov/views.py
> +                    transcript_measurement[measurement_type[0]]],
is this extra indentation PEP8 compliant?

(it look horrible to me). Also for line 685/

2021-09-07 07:16 UTC, melferink commented on ExonCov/views.py
>              )
['len'],  should be on the previous line

2021-09-07 07:18 UTC, melferink commented on ExonCov/utils.py
> +from sqlalchemy.orm import joinedload
joinedload is not used in utils.

2021-09-07 07:19 UTC, melferink requested changes
Couple of general remarks

2021-09-07 09:50 UTC, ellendejong commented on ExonCov/views.py
>              )
Since I copy-pasted the code from views.py and this format was used, I suspect lines were reformatted automatically based on PEP8 rule 80 characters per line. However, this also depends on settings of the editor. I changed format :)

2021-09-07 09:50 UTC, ellendejong commented on ExonCov/views.py
> +                    transcript_measurement[measurement_type[0]]],
I changed format.
However, every time you split a line and it is part of the same statement, you need to indent to show the lines belong together. In this example, that is the case, because two items within list.

2021-09-08 11:48 UTC, melferink commented on ExonCov/cli.py
> +    def retrieve_and_print_transcript_measurements(self, query, measurement_type):
No comment on this. Maybe something to consider later (with @rernst )

2021-09-08 13:18 UTC, melferink approved these changes
Agree with the new changes

2021-10-07 09:06 UTC, rernst reviewed
Some code style comments, please make sure to follow existing code style. Also newline usage is a bit to much, which makes code hard to read. See also: https://dev.azure.com/umcu/LAB-Bioinformatics-Genetics/_wiki/wikis/Bioinformatics-Genetics.wiki/1267/Python?anchor=code-style

2021-10-07 09:06 UTC, rernst commented on ExonCov/views.py
> +        measurements=transcript_measurements)
No newline needed, occurs multiple times.

2021-10-07 09:06 UTC, rernst commented on ExonCov/views.py
> +        measurement_type_form.measurement_type.choices).get(measurement_type_form.data['measurement_type'])]
```python
measurement_type = [
   measurement_type_form.data['measurement_type'], 
   dict(measurement_type_form.measurement_type.choices).get(measurement_type_form.data['measurement_type'])
]
```

2021-10-07 09:38 UTC, ellendejong commented on ExonCov/utils.py
> +    elif isinstance(keys, str):
True. However, if will enter the first if statement in that case.

I will change it to None.

2021-11-01 12:28 UTC, rernst commented on ExonCov/views.py
> +from .utils import get_summary_stats, get_summary_stats_multi_sample, weighted_average
I think both are good, to comply with existing code I think we should use # 2.

2021-11-01 13:09 UTC, rernst requested changes

2021-11-01 13:09 UTC, rernst commented on ExonCov/cli.py
> +            panel_cov_stats = utils.retrieve_coverage(measurements=panels_measurements, keys=[panel], samples=ss_samples)
Did you forget to commit or change `retrieve_coverage`? I am not seeing it in utils.py

2021-11-01 13:09 UTC, rernst commented on ExonCov/cli.py
> +                panels_measurements[panel]['samples'] = OrderedDict()
Does `panels_measurements[panel]` ever contain something else besides`'samples'`? -> Do you need the extra nested dictonary?

2021-11-01 13:09 UTC, rernst commented on ExonCov/cli.py
> +                panels_measurements[panel]['transcripts'] = OrderedDict()
See comment on line 833.

2021-11-01 13:09 UTC, rernst commented on ExonCov/views.py
> +        ]
move 1 'tab' back.

2021-11-24 12:41 UTC, ellendejong commented on ExonCov/cli.py
> +from sqlalchemy.orm.exc import NoResultFound
As discussed, I could not import `NoResultFound` from `sqlalchemy.exc` and still use `SQLAlchemy==1.3.5`.

2021-11-26 14:19 UTC, rernst approved these changes

2021-11-26 14:20 UTC, merged